services:
  client:
    build: ./client
    container_name: shopmrkin_client
    environment:
      VITE_GENERATE_OAUTH_URL: ${PROTOCOL}://${SERVER_NAME}/api/auth/google-redirect-url?redirect_uri=${PROTOCOL}://${CLIENT_NAME}/auth/google/callback
      VITE_GOOGLE_CALLBACK_BE_URL: ${PROTOCOL}://${SERVER_NAME}/api/auth/login-google
      VITE_BACK_END_HOST: ${PROTOCOL}://${SERVER_NAME}
    expose:
      - "9000"
    develop:
      watch:
        # sync new source code
        - action: sync
          path: ./client/src
          target: /app/src

        # rebuild when install new package
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./client/package-lock.json

        # restart when config change
        - action: sync+restart
          path: ./client
          target: /app
          ignore:
            - ./client/src
            - ./client/node_modules/
            - ./client/package.json
            - ./client/package-lock.json

  server:
    build: ./server
    container_name: shopmrkin_server
    environment:
      SERVER_NAME: ${SERVER_NAME}
      PORT: 8000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/shopmrkin_dev
    expose:
      - "8000"
    develop:
      watch:
        # sync new source code
        - action: sync
          path: ./server/src
          target: /app/src

        # rebuild when install new package
        - action: rebuild
          path: ./server/package.json
        - action: rebuild
          path: ./server/package-lock.json

        # restart when config change
        - action: sync+restart
          path: ./server
          target: /app
          ignore:
            - ./server/src
            - ./server/public
            - ./server/node_modules/
            - ./server/package.json
            - ./server/package-lock.json
    volumes:
      - ./server/public:/app/public

  postgres:
    image: ankane/pgvector:v0.5.0
    container_name: pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # expose for testing
    volumes:
      - postgres_db:/var/lib/postgresql/data

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  postgres_db:
